TrashCollector/Models/Customer.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace TrashCollector.Models
{
    public class Customer
    {
        [Key]
        public int CustomerId { get; set; }

        [Display(Name = "First Name")]
        public string FirstName { get; set; }

        [Display(Name = "Last Name")]
        public string LastName { get; set; }

        [Display(Name = "Address Line 1")]
        public string Street { get; set; }

        public string City { get; set; }

        public string State { get; set; }

        [Display(Name = "Zip Code")]
        public int ZipCode { get; set; }

        [Display(Name = "Balance Owed")]
        [DisplayFormat(DataFormatString = "{0:C}")]
        public double BalanceOwed { get; set; }

        [ForeignKey("IdentityUser")]
        public string IdentityUserId { get; set; }
        public IdentityUser IdentityUser { get; set; }
    }
}

TrashCollector/Controllers/DatePickupsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TrashCollector.Data;
using TrashCollector.Models;

namespace TrashCollector.Controllers
{
    public class DatePickupsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public DatePickupsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: DatePickups
        public async Task<IActionResult> Index()
        {
            var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            var applicationDbContext = _context.DatePickups.Include(w => w.Customer)
                                         .Where(c => c.Customer.IdentityUserId == userId);

            return View(await applicationDbContext.ToListAsync());
        }

        // GET: DatePickups/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: DatePickups/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("DatePickupId,Completed,Date,CustomerId")] DatePickup datePickup)
        {
            if (ModelState.IsValid)
            {
                Customer customer = _context.Customers
                     .Where(c => c.IdentityUserId == this.User.FindFirstValue(ClaimTypes.NameIdentifier)).SingleOrDefault();
                datePickup.CustomerId = customer.CustomerId;

                _context.Add(datePickup);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(datePickup);
        }

        // GET: DatePickups/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var datePickup = await _context.DatePickups.FindAsync(id);
            if (datePickup == null)
            {
                return NotFound();
            }
            return View(datePickup);
        }

        // POST: DatePickups/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("DatePickupId,Completed,Date,CustomerId")] DatePickup datePickup)
        {
            if (id != datePickup.DatePickupId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    Customer customer = _context.Customers
                                        .Where(c => c.IdentityUserId == this.User.FindFirstValue(ClaimTypes.NameIdentifier)).SingleOrDefault();
                    datePickup.CustomerId = customer.CustomerId;

                    _context.Update(datePickup);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DatePickupExists(datePickup.DatePickupId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(datePickup);
        }

        // GET: DatePickups/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var datePickup = await _context.DatePickups.Include(d => d.Customer).FirstOrDefaultAsync(m => m.DatePickupId == id);
            if (datePickup == null)
            {
                return NotFound();
            }

            return View(datePickup);
        }

        // POST: DatePickups/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var datePickup = await _context.DatePickups.FindAsync(id);
            _context.DatePickups.Remove(datePickup);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DatePickupExists(int id)
        {
            return _context.DatePickups.Any(e => e.DatePickupId == id);
        }
    }
}

TrashCollector/Controllers/SuspendPickupsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TrashCollector.Data;
using TrashCollector.Models;

namespace TrashCollector.Controllers
{
    public class SuspendPickupsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public SuspendPickupsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: SuspendPickups
        public async Task<IActionResult> Index()
        {
            var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            var applicationDbContext = _context.SuspendPickups.Include(w => w.Customer)
                                         .Where(c => c.Customer.IdentityUserId == userId);

            return View(await applicationDbContext.ToListAsync());
        }

        // GET: SuspendPickups/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: SuspendPickups/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("SuspendPickupId,Completed,StartDate,EndDate,CustomerId")] SuspendPickup suspendPickup)
        {
            if (ModelState.IsValid)
            {
                Customer customer = _context.Customers
                     .Where(c => c.IdentityUserId == this.User.FindFirstValue(ClaimTypes.NameIdentifier)).SingleOrDefault();
                suspendPickup.CustomerId = customer.CustomerId;

                _context.Add(suspendPickup);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(suspendPickup);
        }

        // GET: SuspendPickups/Edit
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var suspendPickup = await _context.SuspendPickups.FindAsync(id);
            if (suspendPickup == null)
            {
                return NotFound();
            }
            return View(suspendPickup);
        }

        // POST: SuspendPickups/Edit
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("SuspendPickupId,Completed,StartDate,EndDate,CustomerId")] SuspendPickup suspendPickup)
        {
            if (id != suspendPickup.SuspendPickupId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    Customer customer = _context.Customers
                         .Where(c => c.IdentityUserId == this.User.FindFirstValue(ClaimTypes.NameIdentifier)).SingleOrDefault();
                    suspendPickup.CustomerId = customer.CustomerId;

                    _context.Update(suspendPickup);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SuspendPickupExists(suspendPickup.SuspendPickupId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(suspendPickup);
        }

        // GET: SuspendPickups/Delete
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var suspendPickup = await _context.SuspendPickups.Include(s => s.Customer)
                                      .FirstOrDefaultAsync(m => m.SuspendPickupId == id);
            if (suspendPickup == null)
            {
                return NotFound();
            }

            return View(suspendPickup);
        }

        // POST: SuspendPickups/Delete
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var suspendPickup = await _context.SuspendPickups.FindAsync(id);
            _context.SuspendPickups.Remove(suspendPickup);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SuspendPickupExists(int id)
        {
            return _context.SuspendPickups.Any(e => e.SuspendPickupId == id);
        }
    }
}

TrashCollector/Controllers/WeeklyPickupsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TrashCollector.Data;
using TrashCollector.Models;
using TrashCollector.Controllers;

namespace TrashCollector.Controllers
{
    public class WeeklyPickupsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public WeeklyPickupsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: WeeklyPickups
        public async Task<IActionResult> Index()
        {
            var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            var applicationDbContext = _context.WeeklyPickups.Include(w => w.Customer).Include(w => w.WeekDay)
                                         .Where(c => c.Customer.IdentityUserId == userId);

            // If current user doesn't have a weekly pickup, go right to Create() action.
            if (applicationDbContext.Count() == 0)
                return RedirectToAction(nameof(Create));

            return View(await applicationDbContext.ToListAsync());
        }

        // GET: WeeklyPickups/Create
        // Only called once from customer index if customer doesn't have a weekly pickup.
        public IActionResult Create()
        {
            ViewData["WeekDayId"] = new SelectList(_context.WeekDays, "WeekDayId", "Day");
            return View();
        }

        // POST: WeeklyPickups/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("WeeklyPickupId,Completed,WeekDayId,CustomerId,EmployeeId")] WeeklyPickup weeklyPickup)
        {
            if (ModelState.IsValid)
            {
                Customer customer = _context.Customers
                                     .Where(c => c.IdentityUserId == this.User.FindFirstValue(ClaimTypes.NameIdentifier)).SingleOrDefault();
                weeklyPickup.CustomerId = customer.CustomerId;

                _context.Add(weeklyPickup);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            ViewData["WeekDayId"] = new SelectList(_context.WeekDays, "WeekDayId", "Day", weeklyPickup.WeekDayId);
            return View(weeklyPickup);
        }

        // GET: WeeklyPickups/Edit
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var weeklyPickup = await _context.WeeklyPickups.FindAsync(id);
            if (weeklyPickup == null)
            {
                return NotFound();
            }
            ViewData["WeekDayId"] = new SelectList(_context.WeekDays, "WeekDayId", "Day", weeklyPickup.WeekDayId);
            return View(weeklyPickup);
        }

        // POST: WeeklyPickups/Edit
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("WeeklyPickupId,Completed,WeekDayId,CustomerId")] WeeklyPickup weeklyPickup)
        {
            if (id != weeklyPickup.WeeklyPickupId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    Customer customer = _context.Customers
                        .Where(c => c.IdentityUserId == this.User.FindFirstValue(ClaimTypes.NameIdentifier)).SingleOrDefault();
                    weeklyPickup.CustomerId = customer.CustomerId;

                    _context.Update(weeklyPickup);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!WeeklyPickupExists(weeklyPickup.WeeklyPickupId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["WeekDayId"] = new SelectList(_context.WeekDays, "WeekDayId", "Day", weeklyPickup.WeekDayId);
            return View(weeklyPickup);
        }

        // GET: WeeklyPickups/Delete
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var weeklyPickup = await _context.WeeklyPickups.Include(w => w.Customer).Include(w => w.WeekDay)
                                     .FirstOrDefaultAsync(m => m.WeeklyPickupId == id);
            if (weeklyPickup == null)
            {
                return NotFound();
            }

            return View(weeklyPickup);
        }

        // POST: WeeklyPickups/Delete
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var weeklyPickup = await _context.WeeklyPickups.FindAsync(id);
            _context.WeeklyPickups.Remove(weeklyPickup);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index), "Customers");
        }

        private bool WeeklyPickupExists(int id)
        {
            return _context.WeeklyPickups.Any(e => e.WeeklyPickupId == id);
        }
    }
}

TrashCollector/Views/Customers/Create.cshtml
@model TrashCollector.Models.Customer

@{
    ViewData["Title"] = "Create: Customer";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create Customer Profile</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Street" class="control-label"></label>
                <input asp-for="Street" class="form-control" />
                <span asp-validation-for="Street" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="City" class="control-label"></label>
                <input asp-for="City" class="form-control" />
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="State" class="control-label"></label>
                <input asp-for="State" class="form-control" />
                <span asp-validation-for="State" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ZipCode" class="control-label"></label>
                <input asp-for="ZipCode" class="form-control" />
                <span asp-validation-for="ZipCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TrashCollector/Views/Customers/Delete.cshtml
@model TrashCollector.Models.Customer

@{
    ViewData["Title"] = "Delete: Customer";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete Customer</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Street)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Street)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.City)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.City)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.State)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.State)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ZipCode)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ZipCode)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="CustomerId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to Customer Home</a>
    </form>
</div>

TrashCollector/Views/Customers/Details.cshtml
@model TrashCollector.Models.Customer

@{
    ViewData["Title"] = "Details: Customers";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Customer Details</h1>

<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Street)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Street)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.City)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.City)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.State)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.State)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ZipCode)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ZipCode)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BalanceOwed)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BalanceOwed)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.CustomerId">Edit</a> |
    <a asp-action="Index">Back to Customer Home</a>
</div>

TrashCollector/Views/Customers/Edit.cshtml
@model TrashCollector.Models.Customer

@{
    ViewData["Title"] = "Edit: Customer";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit Customer</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="CustomerId" />
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Street" class="control-label"></label>
                <input asp-for="Street" class="form-control" />
                <span asp-validation-for="Street" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="City" class="control-label"></label>
                <input asp-for="City" class="form-control" />
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="State" class="control-label"></label>
                <input asp-for="State" class="form-control" />
                <span asp-validation-for="State" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ZipCode" class="control-label"></label>
                <input asp-for="ZipCode" class="form-control" />
                <span asp-validation-for="ZipCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to Customer Home</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TrashCollector/Views/Customers/Index.cshtml
@model IEnumerable<TrashCollector.Models.Customer>

@{
    ViewData["Title"] = "Home: Customer";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Customer Home</h1>

<p>
    <a asp-action="Index" asp-controller="WeeklyPickups">Schedule Weekly Pickup</a>  |
    <a asp-action="Index" asp-controller="DatePickups">Schedule One-time Pickup</a>  |
    <a asp-action="Index" asp-controller="SuspendPickups">Suspend Pickups</a>
</p>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Street)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.City)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.State)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ZipCode)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Street)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.City)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.State)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ZipCode)
            </td>
        <td>
            <a asp-action="Details" asp-route-id="@item.CustomerId">Details</a> |
            <a asp-action="Edit" asp-route-id="@item.CustomerId">Edit</a> |
            <a asp-action="Delete" asp-route-id="@item.CustomerId">Delete</a>
        </td>
        </tr>
}
    </tbody>
</table>